services:
  postgres-dev:
    image: postgres:17.2-alpine
    container_name: postgres-dev
    restart: always
    expose:
      - "5432:5432"
    environment:
      POSTGRES_DATA: /var/lib/postgresql/data
    env_file:
      - .env
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
      interval: 10s
      timeout: 5s
      retries: 5

  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      postgres-dev:
        condition: service_healthy
    volumes:
      - ./src:/app/src

volumes:
  postgres-dev-data: