# Generated by Django 5.2.5 on 2025-08-17 16:13

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveSmallIntegerField(db_index=True, unique=True, validators=[django.core.validators.RegexValidator(message='Code must be 1 or 2 digits followed by a capital letter (e.g., 1A, 12B).', regex='^\\d{1,2}[A-Z]$')], verbose_name='Class number')),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('maths', models.IntegerField(blank=True, null=True)),
                ('english', models.IntegerField(blank=True, null=True)),
                ('physics', models.IntegerField(blank=True, null=True)),
                ('chemistry', models.IntegerField(blank=True, null=True)),
                ('history', models.IntegerField(blank=True, null=True)),
                ('geography', models.IntegerField(blank=True, null=True)),
                ('literature', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(blank=True, choices=[('MATH', 'Math'), ('ENGLISH', 'English'), ('PHYSICS', 'Physics'), ('CHEMISTRY', 'Chemistry'), ('HISTORY', 'History'), ('GEOGRAPHY', 'Geography'), ('LITERATURE', 'Literature')], db_index=True, default='', max_length=20, null=True, verbose_name='Subject')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('_class', models.OneToOneField(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, related_name='students', to='api.class', verbose_name='Class')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
    ]
