# Generated by Django 4.2.6 on 2024-08-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_class_student_teacher_delete_choice_delete_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='number',
            field=models.IntegerField(),
        ),
    ]
